### ISSUE TITLE
Idea on implementation: Priority system for missions

### ISSUE THREAD

**Issue by CSumm** [factn/resilience-app#104]
I'm taking on the challenge of implementing priorities into missions. I have several ideas:
- requesters submit form and the description of task is analyzed for certain keywords (for now we hand code a simple string.contains solution, then later on look into an ML library)
- based on keywords we add up a tally. If it is below a certain value its of lesser priority. If its of a higher value, its higher priority. However, I'm thinking of marking from 1 being the highest, and 5 the lowest
- would it be possible to integrate the priority values into the firebase schema, so that way when we call the missions we can also pull up its priorities at ease?

**Comment by mat10tng** [comment]
I suggest we wait until we know where the organizer will be in this situation. I suspect, that we will have a queue of missions which then will be manually prioritized by the organizer. Instead of prioritizing this by number, maybe we can do ml -> tag the mission with correct tag so that it will be easier for the organizer to work with, such as ...text.. food... -> tag with -food-

**Comment by CSumm** [comment]
Sounds good. Ill hold off on that ticket for now and check out something else.
