### ISSUE TITLE
As a temporary measure can we write some sort of CI integration to reset the db every so often??

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#260]
@mat10tng  has a great wee script that populates some fake data into our crazy shared development db set up (at firebase).

Obviously the right thing long term is that every developer has their own db and integrations or some sort of mock or something.. but as a temporary measure can we write a script that resets all the data in dev every so often? Like every 2 hours or something? 

I am not entirely sure where the code @mat10tng has been running actually is but maybe you can tell us or maybe we can find it. It was python once upon a time.

**Comment by mat10tng** [comment]
ehm, it is in my branch still which is feat/story-116-missions-map-list-view
in the root directory
/scheme/data.py

**Comment by rainrivas** [comment]
@mat10tng just so i'm understanding the flow here, you're running `data.py` to build your dataset, then you're running the `uploadMock.js` to push the data up to firefbase yes?

**Comment by mat10tng** [comment]
Yeah you're right. Also, I wrote that in according to scheme.ts in the
model folder. But that scheme might change. I am just do manuall check for
now though

**Comment by rainrivas** [comment]
@mat10tng @utunga  I'm getting pretty close to cracking this egg. Workingo n a fork to test out some github actions to execute the python script and then the nodejs script. I need to find out how we are meant to load secrets & environment variables so that the file so that we can node script can correctly update the DB.

**Comment by rainrivas** [comment]
Here is a sample of the seed action running -- https://github.com/rainrivas/resilience-app/actions/runs/82457841

Currently clocked to run every minute but I will be changing it to run every 2 hours as @utunga suggested

**Comment by utunga** [comment]
That looks super cool @rainrivas. I guess my only question is what to do from here to run this on our repo? Or rather our dev db? Is it already running?

**Comment by rainrivas** [comment]
@utunga It's not currently running on our DB since I do not have the secret keys to update firebase. We should be able to get this running by creating the same workflow in this repo -- i can open a PR for this. I need to do a quick test on my fork for using Secrets from GH settings to pass into the workflow. If I get this working (will test tomorrow) I will connect with you guys to get the appropriate secret file added to the repo. I'll only need the secret name so I can configure `uploadMock.js` to use that to create the connection

**Comment by utunga** [comment]
@rainrivas cool... creating a PR sounds good. Does github have a function for storing secrets in env variables in a secure way like the way that heroku and such do?

**Comment by rainrivas** [comment]
@utunga We should be able to make use of the "Secrets" option under the project settings -- [GH Docs](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

Relevant Bit:
> Secrets are encrypted environment variables that you create in a repository for use with GitHub Actions. GitHub uses a libsodium sealed box to help ensure that secrets are encrypted before they reach GitHub, and remain encrypted until you use them in a workflow.
To make a secret available to an action, you must set the secret as an input or environment variable in the workflow file.

I'm going to tweak my fork to make use of some placeholder secret for the firebase-admin connection and modify that js script to read an environment variable set by the workflow.

**Comment by utunga** [comment]
Sounds great.

Miles Thompson
NZ: +64 2153 9843 | E: utunga@gmail.com | W: http://goodbright.nz
