### ISSUE TITLE
AuthenticaAccountPhoneNumberPage

### ISSUE THREAD

**Issue by mat10tng** [factn/resilience-app#34]
![image](https://user-images.githubusercontent.com/3273671/77322433-ffb3c880-6d13-11ea-8ef0-3bd862f56dc8.png)

Ignore color, go with hardcoded if you like for now, we will input theme later
Making sure you are using existing component, if it not existing, you can ignore it for now
maxwidth of container to 600px!

app/page/AccountAuthPhoneConfirm

AccountAuthPhoneConfirm.js
AccountAuthPhone.style.js
AccountAuthPhone.test.js
index.js // export default here

**Comment by considine** [comment]
I can take this one

**Comment by utunga** [comment]
@considine I realize things have been moving fast beneath you. sorry about that. is this one ready to close because it got fixed elsewhere? Also, please feel free to come back! We've gotten a bit better organised now so will be able to make use of your skills! Food is getting delivered on the groud and we need to scale out this app asap so we can start to handle the many communities about to hjoing
