### ISSUE TITLE
Organizer mission control navigation

### ISSUE THREAD

**Issue by DAHuerta** [factn/resilience-app#396]
**Description**

As an organizer, on a desktop device, I can get to and from mission control (navigation)

[Airtable #160](https://airtable.com/tblRjd2McKgRW9MKj/viwlRRNI0PZIxrGkc/rec2JtXXhSV2NfdVF?blocks=hide)

**Comment by marekdano** [comment]
I can work on this ticket.

**Comment by utunga** [comment]
Feel like there was a comment about this somewhere else but, at the risk of being redundant.

1. That would be great, thanks @marekdano 
2. For MVP.0 we decided it was a bit tricky to have the Organiser Dashboard open up by default. 
3. If you edit a user, manually, in the firebase back end it is possible to to set organiser=True flag. (which will suffice for MVP0).
4. If you are an organizer there is already a link in the sidebar to the [organiser dashboard](https://resilience-app.herokuapp.com/dashboard) - so that bit is done.
5. What is still missing is there is currently no way 'back' from organiser dashboard to the 'normal' home. Perhaps we need a design for that, or perhaps you can just think of something that works and looks good?

**Comment by marekdano** [comment]
thanks, @utunga. I had a discussion about it with @mat10tng. I'm adding a link to get back from dashboard (Mission control) to app. Is it ok if the link has name of `App`?

**Comment by utunga** [comment]
@marekdano sorry for delay I honestly dont quite know what you are asking.. but if the name you are thinking of is "Resilience App" then I guess, sure that would be fine. If you mean some other name, make a call. Thanks

**Comment by marekdano** [comment]
> @marekdano sorry for delay I honestly dont quite know what you are asking.. but if the name you are thinking of is "Resilience App" then I guess, sure that would be fine. If you mean some other name, make a call. Thanks

no worries, @utunga. I'll go for your suggested name `Resilience App`. If it's gonna be different we can do that in my next PR.

**Comment by marekdano** [comment]
I've just checked the latest version of `resilience-app` on my local machine and I can confirm that the link from `dashboard` page to get to `missions` page is already implemented. Now I can get from any page in `resilience-app` to `dashboard` and back. 
I think the `Airtable #160` can be marked as `Done`. 
Can you confirm my thoughts?

**Comment by karenkun** [comment]
Can confirm it does goes to the correct page.
