### ISSUE TITLE
Update hamburger user menus to reflect the appropriate links for launch.

### ISSUE THREAD

**Issue by karenkun** [factn/resilience-app#489]
Recipient's menu should have these link:
https://www.figma.com/file/GLg0zPNnwMEGIb9TytCrxQ/Resilience-App?node-id=3480%3A5711
- note that the volunteer dash link is "Help Volunteer" which goes to volunteer registration

Volunteer's menu should have these links:
https://www.figma.com/file/GLg0zPNnwMEGIb9TytCrxQ/Resilience-App?node-id=3480%3A5547
- note that there is still a "Requests" menu link which goes to the requests dashboard
- hide features that are incomplete (ie.  "Volunteer Status")
----
- "Powered by Resilience" links to 'About Us'

**Comment by amylo** [comment]
I will do this once I complete the permissions and routing implementation.

**Comment by amylo** [comment]
I'm thinking of implementing a "logout" page that will:

1. Handle the firebase.logout() in one place
2. Display some loading message while the logout request is made
3. Redirect to home screen once that's done

because currently when logging out, you see a brief glimpse of the Missions screen before it shows the public home screen, which is a pretty janky user experience.

**Comment by mat10tng** [comment]
this is done?
