### ISSUE TITLE
New account doesn't have profile in the menu

### ISSUE THREAD

**Issue by utunga** [factn/resilience-app#584]
**Steps to reproduce** 

1.  Logged out at https://mutualaid-757f6.web.app/
2. Click sign in. Sign in with Google account. 
3. See this page

**Expected**

Access to the profile so I can add a phone number etc

**Actual**

Profile is not available in the menu

![image](https://user-images.githubusercontent.com/166867/82299569-c9d84b00-9a09-11ea-8036-a3b569d81bb1.png)

**Comment by utunga** [comment]
Actually I think this might just be a problem of it being a partial loading thing.

**Comment by amylo** [comment]
> Actually I think this might just be a problem of it being a partial loading thing.

Yeah, it takes the menu a second to verify that the user has logged in and showing the menu items. I can put in a loading progress spinner or something during that verification time so that we don't confuse the users. Though to be fair, a new user isn't going to immediately click on that menu right after logging in ;)

**Comment by utunga** [comment]
Fixed ni #607
